//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFooter
    {
        public int FooterID { get; set; }
        public string FooterTitle { get; set; }
        public string FooterPhone { get; set; }
        public string FooterMail { get; set; }
        public string FooterAdress { get; set; }
    }
}
